spring:
  application:
    name: Task-Management
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Task?createDatabaseIfNotExist=true
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
      display-request-duration: true
      doc-expansion: none

server:
  port: 8001
  servlet:
    context-path: /tasks

cloud:
  aws:
    credentials:
      access-key: ENC(WqTAdVSF6sWjk1yTKfapIT2kIDcfsPo1VSkCQ5Hj7vw=)
      secret-key: ENC(QZnJbstj0x8rkYHFuP1aIKDjHqO5z+L/bxdkd28PvI/gaq8Rcr70fw/uirasDf04q7y5bisRhW0=)
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: job-check

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
